# Generated by Django 5.0.6 on 2024-06-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_currency_main_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="converted_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
