# Generated by Django 5.0.6 on 2024-06-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_account_converted_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="conversion_rate_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
