# Generated by Django 5.0.6 on 2024-06-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_account_conversion_rate_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="conversion_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="converted_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
