# Generated by Django 5.0.6 on 2024-06-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_account_conversion_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="conversion_rate_task_id",
        ),
    ]
